
/*
    This file is part of "ChoiCo" a web application for designing digital games, written by Marianthi Grizioti for the National and Kapodistrian University of Athens (Educational Technology Lab).
    Copyright (C) 2017-2018.
    ChoiCo is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ChoiCo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Footbar.  If not, see <http://www.gnu.org/licenses/>.
*/
english = {
		name: "English",
	introSubText : "A kit for designing and playing digital games",
	introQuestion: "What would you like to do?",
	designButtonText : "Design a Game",
	playButtonText : "Play Online Games",
	loadButtonText : "Load Game",
	tab1: "Game Interface",
	tab2: "Initial Settings",
	tab3: "Gameplay Rules",
	tab4: "End Rules",
	uploadImgDisc : "Change Background",
	addPointDisc: "Add Point",
	addInstructionsDisc: "Add game instructions",
	deleteIcoDisc : "Delete selected attribute",
	settingsIcoDisc : "Settings of selected attribute",
	addAttributeDisc : "Add Attribute",
	pointsLimitTxt : "Max No of Turns",
	manualDisc : "User Manual",
	contactDisc : "Contact Form",
	homeDisc : "Back to homepage",
	help: "Help",
	home: "Home",
	play: "Play",
	edit: "Edit Game",
	stats: "Statistics",
	download: "Download",
	info: "Instructions",
	generalErrorMessage: "There is a general error in the blocks code. Open the game in design mode to fix it. ",
	variableErrorMessageA: "' is used as variable in your 'Initial Settings' code, but there is no such field in the datatable (You probably deleted it or renamed it in the datatable).",
	variableErrorMessageB: "The game code will not run correctly.",
	variableErrorMessageC: " Replace this variable in the 'Initial Settings' code with the correct one or delete this part of the code.  ",
	variableErrorMessageEndA:  "' is used as variable in the 'End Rules' code, but there is no such field in the datatable (You probably deleted it or renamed it in the datatable).   ",
	variableErrorMessageEndB:  "The game code will not run correctly. ",
	variableErrorMessageEndC:  " Replace this variable in the 'End Rules' code with the correct one or delete this part of the code.  ",
	variableErrorMessageGameplayA:  "' is used as variable in the 'Gameplay Rules' code, but there is no such field in the datatable (You probably deleted it or renamed it in the datatable).   ",
	variableErrorMessageGameplayB:  "The game code will not run correctly. ",
	variableErrorMessageGameplayC:  " Replace this variable in the 'Gameplay Rules' code with the correct one or delete this part of the code.  ",
	notNumberMessageA: "' has no numerical value as a starting value.",
	notNumberMessageB: " The field will show as 'undefined' and you will not be play the game correctly.",
	notNumberMessageC: "  Open the tab 'Initial Settings' and set up a number as starting value for this field.",
	notInitialValueA: "' has no starting value.",
	notInitialValueB: " The field will show as 'undefined' and you will not be play the game correctly.",
	notInitialValueC: " Open the tab 'Initial Settings' and use a 'set' command to set a starting value for this field.",
	tab1MessageA : "The game fields have no initial values. ",
	tab1MessageB: "The game fields will show as 'undefined'and you will not be play the game correctly.",
	tab1MessageC: "Open the tab 'Initial Settings' and set up the initial values for the game fields", 
	tab3MessageA: "Your game has no ending rules.",
	tab3MessageB: "The game will never end.",
	tab3MessageC: "Open the tab 'End Rules' and set up some ending rules for the game by using a conditional and the game over blocks.",
	markersMessageA : "The game has no markers on the map.",
	layersRemoveMessage: "Are you sure you want to remove this layer?",
	homeMessage : "ATTENTION: By going to homepage, all your current progress will be lost! Go to homepage?",
	typeLabel : "Attribute Type",
	visibilityLabel : "Visibility to player",
	envyText : "Game for sustainability and environmental ethics ",
	perfectVilleText: " Game for a citizen's choices in a city ",
	perfectVilleGame: "myGame.openInstance('perfectVille_Eng', 4);",

	shoppingGame: "myGame.openInstance('shopping_Eng', 4);",

	sustTextiles: "myGame.openInstance('sustTextiles_Eng', 4);",
			ethics: "window.location = 'http://etl.ppp.uoa.gr/choico/?ethics_Gr'",
	composte: "myGame.openInstance('composte_Eng', 4);",
	womanity: "myGame.openInstance('womanity_Eng', 4);",
	sustTextilesText: " A game for sustainability in e-textiles industry",
	badiText: " A game for balanced diet ",
	// mpText: " A game for ancient Greek ",
	 supermarketText: " A game for mathematical relations  ",
	 covidText: "A game about Covid-19 Pandemic",
	 //pcText: " Game for computer architecture ",
 composteText: " A game for chemistry and composting ",
 womanityText: " A game for a woman's everyday life ",
	 ethicsText : " Game for work ethic",
	 eatingTextHB : "A half-baked game about healthy food choices",
	 eatingText: "A game about healthy food choices",
	 eatingOutHBGame: "myGame.openInstance('eatingOutHB_Eng', 4);",
 chefText: "A half-baked game about Computational Thinking and business management",
 chefGame: "myGame.openInstance('CTChef_Eng', 4);",
 schoolText: "A mod of the game 'Eating Out', created by students ",
 europeText: "A mod of the game 'Eating Out', created by students ",
  europe: "myGame.openInstance('europe_Eng', 4);",
	  school: "myGame.openInstance('school_Eng', 4);",
		eatingOutGame:  "myGame.openInstance('eatingOut_Eng', 4);",
		livingInAthens: "myGame.openInstance('livinginAthens_Eng', 4);",
		theBeeKeeper: "myGame.openInstance('theBeeKeeper_Eng', 4);",
	covidGame:  "myGame.openInstance('covid19survivor_Eng', 4);",
	smartJacket:  "myGame.openInstance('smartJacket_Eng', 4);",
			nayplioGame:  "myGame.openInstance('nayplio_Gr', 4);",
			escapePlan:  "myGame.openInstance('escapePlan_Gr', 4);",
					ancientGreek:  "myGame.openInstance('ancient_Gr', 4);",
	envyGame:  "myGame.openInstance('envyCity_Eng', 4);",
			smartJacketText: "A game for the everyday use of an e-textile device ",
 manualUrl: "http://etl.ppp.uoa.gr/choico/manuals/choico_user_manual_EN.pdf",
	//PLAYMODE
	pointInfoText : "Point Information",
			gameStartedText : "The game has started",
			gameValues: "Game Values",
		pointsVisited: "No of Choices",
	selectButton : "Select Point",
	gameStatusText: "Game Status",
	deletePointText : "Delete Point",
		settingsPoint: "Point Settings",
		instructions : "Game Instructions",
		gameOverMessage: "The game has ended!",
		gameOverQuestion: "What would you like to do?",
		editText: "Edit Game",
		playAgainText: "Play Again",
		scoreText: "Show score and statistics",
		gameEnded: "The game has ended!",
		gameEndedQuestion: "What would you like to do?",
		letsPlayText: "Let's Play!",
		gameProgressText: "Game Statistics",
		currentValuesText: "Current field values",
		choiceHistoryText: "Choices history",
		downloadScoreText: "Download Score",
				backBtnText: "Back",
	instructionsText: "Game Instructions",
	layersText: "Map Layers Settings",
	loadingMessage: "The game is loading...Please wait",
	layersTitle: "Layers",
	newLayer: "New Layer",
	pointSettingsTitle: "Settings of Point: ",
	appearOnLayer: "Appears on Layer: ",
			affectScore: "Selecting this point will NOT affect the score and it will not be counted to the visited points: ",
	popUpMessage : "Game Ends! You have reached the maximum number of points <br>",
	gameInstructionsDefault: "Click on a point to see its consequences on the info point table. Click select point to select it. Your score is shown on the game values table",
	selBoxText: "Text",
	selBoxNum: "Number",
	selBoxUrl: "Url",
	selBoxDate: "Date",
	selBoxImage: "Image",
	visBoxVisible: "Visible",
	visBoxHidden: "Hidden"
}

greek = {
	name: "Greek",
	introSubText : "Σχεδίασε και παίξε ψηφιακά παιχνίδια επιλογών και επιπτώσεων",
		introQuestion: "",
	designButtonText : "Σχεδίασε ένα παιχνίδι",
	playButtonText : "Παίξε παιχνίδια online",
	loadButtonText : "Φόρτωσε ένα παιχνίδι",
	tab1: "Διεπαφή Παιχνιδιού",
	tab2: "Αρχικές Ρυθμίσεις",
	tab3: "Κανόνες Ροής",
	tab4: "Κανόνες Τερματισμού",
	uploadImgDisc : "Αλλαγή Υποβάθρου",
	addPointDisc: "Προσθήκη Σημείου",
	addInstructionsDisc: "Προσθήκη οδηγιών παιχνιδιού",
	deleteIcoDisc : "Διαγραφή επιλεγμένου πεδίου",
	settingsIcoDisc : "Ρυθμίσεις επιλεγμένου πεδίου",
	settingsPoint: "Ρυθμίσεις Σημείου",
	addAttributeDisc : "Προσθήκη Πεδίου",
	pointsLimitTxt : "Μέγιστο Όριο Κινήσεων",
	manualDisc : "Εγχειρίδιο Χρήσης",
	contactDisc : "Φόρμα Επικοινωνίας",
	homeDisc : "Επιστροφή στην Αρχική Σελίδα",
	instructions : "Οδηγίες Παιχνιδιού",
	layersText: "Ρυθμίσεις Στρώσεων Χάρτη",
	layersTitle: "Στρώσεις",
	newLayer: "Νέα Στρώση",
		pointSettingsTitle: "Ρυθμίσεις του σημείου: ",
		appearOnLayer: "Εμφανίζεται στη στρώση: ",
		affectScore: "Η επίλογη αυτού του σημείου δεν θα επηρεάζει το σκορ και δεν θα μετράει στο σύνολο σημείων: ",
	help: "Βοήθεια",
	home: "Αρχική",
	play: "Παίξε",
	edit: "Σχεδίαση",
	stats: "Στατιστικά",
	download: "Αποθήκευση",
	info: "Πληροφορίες",

 manualUrl: "http://etl.ppp.uoa.gr/choico/manuals/choico_user_manual_GR.pdf",
 	generalErrorMessage: "Υπάρχει το παρακάτω σφάλμα στον κώδικα! Άνοιξε το παιχνίδι σε λειτουργία σχεδιασμού για να το διορθώσεις. ",
	 variableErrorMessageA: "' υπάρχει ως μεταβλητή στον κώδικα, αλλά δεν υπάρχει ως στήλη στον πίνακα (Πιθανόν να το διέγραψες ή να το μετονόμασες στον πίνακα, χωρίς να το αλλάξεις στον κώδικα).",
	 variableErrorMessageB: "Το παιχνίδι δεν θα λειτουργήσει σωστά.",
	 variableErrorMessageC: " Αντικατέστησε αυτή τη μεταβλητή στον κώδικα με τη σωστή ή διέγραψε το κομμάτι που την περιλαμβάνει", 
	 notNumberMessageA: "' δεν έχει αριθμό ως αρχική τιμή.",
	 notNumberMessageB: " Το πεδίο θα εμφανίζεται ως 'undefined' και δεν θα μπορείς να παίξεις το παιχνίδι σωστά.",
	 notNumberMessageC: " Άνοιξε την καρτέλα 'Αρχικές Ρυθμίσεις' και όρισε έναν αριθμό ως αρχική τιμή αυτού του πεδίου.",
	 notInitialValueA: "' δεν έχει αρχική τιμή.",
	 notInitialValueB: " Το πεδίο θα εμφανίζεται ως 'undefined' και δεν θα μπορείς να παίξεις το παιχνίδι σωστά.",
	 notInitialValueC: " Άνοιξε την καρτέλα 'Αρχικές Ρυθμίσεις' και χρησιμοποιήσε ένα μπλοκ 'set value' για να ορίσεις την αρχική τιμή αυτού του πεδίου.",
	 tab1MessageA : "Τα πεδία του παιχνιδιού δεν έχουν αρχικές τιμές. ",
	 tab1MessageB: "Τα πεδία θα εμφανίζονται ως 'undefined' και δεν θα μπορείς να παίξεις το παιχνίδι σωστά.",
	 tab1MessageC: "Άνοιξε την καρτέλα 'Αρχικές Ρυθμίσεις' και όρισε την αρχική τιμή κάθε πεδίου χρησιμοποιώντας το μπλοκ 'set value'", 
	 tab3MessageA: "Το παιχνίδι δεν έχει κανόνες τερματισμού.",
	 tab3MessageB: "Το παιχνίδι δεν θα τελειώσει ποτέ.",
	 tab3MessageC: "Άνοιξε την καρτέλα 'Κανόνες Τερματισμού' και προγραμμάτισε κάποιους κανόνες τερματισμού για το παιχνίδι, χρησιμοποιώντας μπλοκ συνθήκης ελέγχου (if) και το μπλοκ 'gameover'",
	 markersMessageA : "Το παιχνίδι δεν έχει σημεία επιλογής πάνω στον χάρτη.",
layersRemoveMessage: "Είσαι βέβαιος/η ότι θέλεις να διαγράψεις αυτό το layer;",
	homeMessage : "ΠΡΟΣΟΧΗ: Πηγαίνοντας στην αρχική σελίδα θα χαθεί το παιχνίδι που σχεδίασες! Συνέχεια στην αρχική σελίδα;",
	typeLabel : "Τύπος Πεδίου",
	visibilityLabel : "Ορατό στον παίκτη",
	envyText : " Παιχνίδι για την αειφορία και την περιβαλλοντική συνείδηση. ",
	perfectVilleText: " Παιχνίδι για τις επιλογές ενός πολίτη στην πόλη του ",
		eatingOutGame:  "myGame.openInstance('eatingOut_Gr', 4);",
	covidGame:  "myGame.openInstance('covid19survivor_Gr', 4);",
	smartJacket:  "myGame.openInstance('smartJacket_Gr', 4);",
	perfectVilleGame:  "myGame.openInstance('perfectVille_Gr', 4);",
	shoppingGame:  "myGame.openInstance('shopping_Gr', 4);",
	sustTextiles:  "myGame.openInstance('sustTextiles_Gr', 4);",
	ancientGreek:  "myGame.openInstance('ancient_Gr', 4);",
	womanity:  "myGame.openInstance('womanity_Gr', 4);",
	ethics:  "myGame.openInstance('ethics_Gr', 4);",
	escapePlan:  "myGame.openInstance('escapePlan_Gr', 4);",
	nayplioGame:  "myGame.openInstance('nayplio_Gr', 4);",
	envyGame:  "myGame.openInstance('envyCity_Gr', 4);",
	eatingOutHBGame:  "myGame.openInstance('eatingOutHB_Gr', 4);",
	chefGame:  "myGame.openInstance('CTChef_Gr', 4);",
					 womanityText: " Παιχνίδι για την καθημερινότητα της σύγχρονης γυναίκας ",
	sustTextilesText: " Παιχνίδι για τη βιωσιμότητα στη βιομηχανία υφασμάτων ",
	badiText: " Παιχνίδι για την ισορροπημένη διατροφή ",
	 mpText: " Παιχνίδι για τα Αρχαία Ελληνικά  ",
	 supermarketText: " Παιχνίδι μαθηματικών σχέσεων  ",
	  covidText: "Παιχνίδι για την πανδημία του Covid-19",
	  ethicsText : " Παιχνίδι γα την επαγγελματική ηθική ",
		eatingTextHB: "Μισοψημένο παιχνίδι για την ισορροπημένη διατροφή",
		eatingText: "Παιχνίδι για την ισορροπημένη διατροφή",
chefText: "Μισοψημένο παιχνίδι για την Υπολογιστική Σκέψη και τη διαχείριση επιχειρήσεων",
schoolText: "Διασκευή μαθητών του παιχνιδιού 'Eating Out'",
europeText: "Διασκευή μαθητών του παιχνιδιού 'Eating Out'",
	//PLAY MODE
	pointInfoText : "Πληροφορίες Σημείου",
		gameStartedText : "Το παιχνίδι ξεκίνησε",
	gameValues: "Τιμές",
	pointsVisited: "Αριθμός Επιλογών",
	selectButton : "Επιλογή Σημείου",
	gameStatusText : "Κατάσταση Παιχνιδιού",
	deletePointText : "Διαγραφή Σημείου",
	gameOverMessage: "Το παιχνίδι τελείωσε!",
		gameOverQuestion: "Τι θα ήθελες να κάνεις;",
		editText: "Επεξεργάσου το παιχνίδι",
		playAgainText: "Παίξε ξανά",
		scoreText: "Δες το σκορ",
		gameEnded: "Τελος Παιχνιδιού!",
				gameEndedQuestion: "Τι θέλεις να κάνεις τώρα;",
				gameProgressText: "Στατιστικά Παιχνιδιού",
				currentValuesText: "Τωρινές τιμές πεδίων",
				choiceHistoryText: "Ιστορικό επιλογών",
						downloadScoreText: "Αποθήκευση σκορ",
						backBtnText: "Πίσω",
			letsPlayText: "Παίξε!",
			instructionsText: "Οδηγίες Παιχνιδιού",
			loadingMessage: "Το παιχνίδι φορτώνει...Παρακαλώ περιμένετε",
	popUpMessage : "Τέλος Παιχνιδιού! Έφτασες το μέγιστο όριο των επιτρεπόμενων κινήσεων <br>",
	gameInstructionsDefault : " Οδηγίες Παιχνιδιού: Κάνε κλίκ σε ένα σημείο για να δεις τις επιπτώσεις του στον πίνακα 'Πληροφορίες σημείου'. Μετά, κάνε κλικ στο κουμπί 'επιλογή σημείου' αν θέλεις να το επιλέξεις. Οι τιμές των παραμέτρων του παιχνιδιού αναγράφονται στον πίνακα 'Τιμές' πάνω από την περιοχή παιχνιδιού.",
	selBoxText: "Κείμενο",
	selBoxNum: "Αριθμός",
	selBoxUrl: "Σύνδεσμος",
	selBoxImage: "Εικόνα",
		selBoxDate: "Ημερομηνία",
	visBoxVisible: "Ορατό",
	visBoxHidden: "Κρυμμένο"
}
