
/*
    This file is part of "ChoiCo" a web application for designing digital games, written by Marianthi Grizioti for the National and Kapodistrian University of Athens (Educational Technology Lab).
    Copyright (C) 2017-2018.
    ChoiCo is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ChoiCo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Footbar.  If not, see <http://www.gnu.org/licenses/>.
*/
english = {
		name: "English",
	introSubText : "A kit for designing and playing digital games",
	introQuestion: "What would you like to do?",
	designButtonText : "Design a Game",
	playButtonText : "Play Online Games",
	loadButtonText : "Load Game",
	tab1: "Game Interface",
	tab2: "Initial Settings",
	tab3: "Gameplay Rules",
	tab4: "End Rules",
	uploadImgDisc : "Change Background",
	addPointDisc: "Add Point",
	addInstructionsDisc: "Add game instructions",
	deleteIcoDisc : "Delete selected attribute",
	settingsIcoDisc : "Settings of selected attribute",
	addAttributeDisc : "Add Attribute",
	pointsLimitTxt : "Max No of Turns",
	manualDisc : "User Manual",
	contactDisc : "Contact Form",
	homeDisc : "Back to homepage",
	help: "Help",
	home: "Home",
	play: "Play",
	edit: "Edit",
	stats: "Statistics",
	download: "Download",
	info: "Info",
	generalErrorMessage: "Error: There is an error in the code. Open the game in design mode to fix it. ",
	variableErrorMessageA: "Error: There is no game field called ",
		variableErrorMessageB: " Remove or replace this variable in your code ",
	tab1Message : "Error: You have not set the Initial Values of your fields in the Initial Settings tab (tab 2)",
	tab3Message: "Warning: You have not set any ending conditions on the tab 'End Rules' (tab 3). The game will never end!",
	markersMessage : "Warning: You have not insert any points on your map.",
	layersRemoveMessage: "Are you sure you want to remove this layer?",
	homeMessage : "ATTENTION: By going to homepage, all your current progress will be lost! Go to homepage?",
	typeLabel : "Attribute Type",
	visibilityLabel : "Visibility to player",
	envyText : "Game for sustainability and environmental ethics ",
	perfectVilleText: " Game for a citizen's choices in a city ",
	perfectVilleGame: "myGame.openInstance('perfectVille_Eng', 4);",

	shoppingGame: "myGame.openInstance('shopping_Eng', 4);",

	sustTextiles: "myGame.openInstance('sustTextiles_Eng', 4);",
			ethics: "window.location = 'http://etl.ppp.uoa.gr/choico/?ethics_Gr'",
	composte: "myGame.openInstance('composte_Eng', 4);",
	womanity: "myGame.openInstance('womanity_Eng', 4);",
	sustTextilesText: " A game for sustainability in e-textiles industry",
	badiText: " A game for balanced diet ",
	// mpText: " A game for ancient Greek ",
	 supermarketText: " A game for mathematical relations  ",
	 covidText: "A game about Covid-19 Pandemic",
	 //pcText: " Game for computer architecture ",
 composteText: " A game for chemistry and composting ",
 womanityText: " A game for a woman's everyday life ",
	 ethicsText : " Game for work ethic",
	 eatingTextHB : "A half-baked game about healthy food choices",
	 eatingText: "A game about healthy food choices",
	 eatingOutHBGame: "myGame.openInstance('eatingOutHB_Eng', 4);",
 chefText: "A half-baked game about Computational Thinking and business management",
 chefGame: "myGame.openInstance('CTChef_Eng', 4);",
 schoolText: "A mod of the game 'Eating Out', created by students ",
 europeText: "A mod of the game 'Eating Out', created by students ",
  europe: "myGame.openInstance('europe_Eng', 4);",
	  school: "myGame.openInstance('school_Eng', 4);",
		eatingOutGame:  "myGame.openInstance('eatingOut_Eng', 4);",
	covidGame:  "myGame.openInstance('covid19survivor_Eng', 4);",
	smartJacket:  "myGame.openInstance('smartJacket_Eng', 4);",
			nayplioGame:  "myGame.openInstance('nayplio_Gr', 4);",
			escapePlan:  "myGame.openInstance('escapePlan_Gr', 4);",
					ancientGreek:  "myGame.openInstance('ancient_Gr', 4);",
	envyGame:  "myGame.openInstance('envyCity_Eng', 4);",
			smartJacketText: "A game for the everyday use of an e-textile device ",
 manualUrl: "http://etl.ppp.uoa.gr/choico/manuals/choico_user_manual_EN.pdf",
	//PLAYMODE
	pointInfoText : "Point Information",
			gameStartedText : "The game has started",
			gameValues: "Game Values",
		pointsVisited: "No of Choices",
	selectButton : "Select Point",
	gameStatusText: "Game Status",
	deletePointText : "Delete Point",
		settingsPoint: "Point Settings",
		instructions : "Game Instructions",
		gameOverMessage: "The game has ended!",
		gameOverQuestion: "What would you like to do?",
		editText: "Edit Game",
		playAgainText: "Play Again",
		scoreText: "Show score and statistics",
		gameEnded: "The game has ended!",
		gameEndedQuestion: "What would you like to do?",
		letsPlayText: "Let's Play!",
		gameProgressText: "Game Statistics",
		currentValuesText: "Current field values",
		choiceHistoryText: "Choices history",
		downloadScoreText: "Download Score",
				backBtnText: "Back",
	instructionsText: "Game Instructions",
	layersText: "Map Layers Settings",
	loadingMessage: "The game is loading...Please wait",
	layersTitle: "Layers",
	newLayer: "New Layer",
	pointSettingsTitle: "Settings of Point: ",
	appearOnLayer: "Appears on Layer: ",
			affectScore: "Selecting this point will NOT affect the score and it will not be counted to the visited points: ",
	popUpMessage : "Game Ends! You have reached the maximum number of points <br>",
	gameInstructionsDefault: "Click on a point to see its consequences on the info point table. Click select point to select it. Your score is shown on the game values table",
	selBoxText: "Text",
	selBoxNum: "Number",
	selBoxUrl: "Url",
	selBoxDate: "Date",
	selBoxImage: "Image",
	visBoxVisible: "Visible",
	visBoxHidden: "Hidden"
}

greek = {
	name: "Greek",
	introSubText : "Σχεδίασε και παίξε ψηφιακά παιχνίδια επιλογών και επιπτώσεων",
		introQuestion: "",
	designButtonText : "Σχεδίασε ένα παιχνίδι",
	playButtonText : "Παίξε παιχνίδια online",
	loadButtonText : "Φόρτωσε ένα παιχνίδι",
	tab1: "Διεπαφή Παιχνιδιού",
	tab2: "Αρχικές Ρυθμίσεις",
	tab3: "Κανόνες Ροής",
	tab4: "Κανόνες Τερματισμού",
	uploadImgDisc : "Αλλαγή Υποβάθρου",
	addPointDisc: "Προσθήκη Σημείου",
	addInstructionsDisc: "Προσθήκη οδηγιών παιχνιδιού",
	deleteIcoDisc : "Διαγραφή επιλεγμένου πεδίου",
	settingsIcoDisc : "Ρυθμίσεις επιλεγμένου πεδίου",
	settingsPoint: "Ρυθμίσεις Σημείου",
	addAttributeDisc : "Προσθήκη Πεδίου",
	pointsLimitTxt : "Μέγιστο Όριο Κινήσεων",
	manualDisc : "Εγχειρίδιο Χρήσης",
	contactDisc : "Φόρμα Επικοινωνίας",
	homeDisc : "Επιστροφή στην Αρχική Σελίδα",
	instructions : "Οδηγίες Παιχνιδιού",
	layersText: "Ρυθμίσεις Στρώσεων Χάρτη",
	layersTitle: "Στρώσεις",
	newLayer: "Νέα Στρώση",
		pointSettingsTitle: "Ρυθμίσεις του σημείου: ",
		appearOnLayer: "Εμφανίζεται στη στρώση: ",
		affectScore: "Η επίλογη αυτού του σημείου δεν θα επηρεάζει το σκορ και δεν θα μετράει στο σύνολο σημείων: ",
	help: "Βοήθεια",
	home: "Αρχική",
	play: "Παίξε",
	edit: "Σχεδίαση",
	stats: "Στατιστικά",
	download: "Αποθήκευση",
	info: "Πληροφορίες",

 manualUrl: "http://etl.ppp.uoa.gr/choico/manuals/choico_user_manual_GR.pdf",
 	generalErrorMessage: "Υπάρχει το παρακάτω σφάλμα στον κώδικα! Άνοιξε το παιχνίδι σε λειτουργία σχεδιασμού για να το διορθώσεις. ",
	variableErrorMessageA: "Ooops: Δεν υπάρχει πεδίο με το όνομα: ",
		variableErrorMessageB: "Διέγραψε ή αντικατέστησε αυτή τη μεταβλητή στην καρτέλα: ",
	tab1Message : "Άνοιξε την καρτέλα 'Αρχικές Ρυθμίσεις' για να επιβεβαιώσεις ότι οι αρχικές τιμές είναι σωστές",
	tab3Message : "Δεν έχεις ορίσει κανόνες τερματισμού (καρτέλα 4). Το παιχνίδι δεν θα τερματίζει ποτέ! Σίγουρα θέλεις να προχωρήσεις;",
	markersMessage : "Δεν έχεις εισάγει κανένα σημείο στη σκηνή του παιχνιδιού. Σίγουρα θέλεις να προχωρήσεις;",
layersRemoveMessage: "Είσαι βέβαιος ότι θέλεις να διαγράψεις αυτό το layer;",
	homeMessage : "ΠΡΟΣΟΧΗ: Πηγαίνοντας στην αρχική σελίδα θα χαθεί το παιχνίδι που σχεδίασες! Συνέχεια στην αρχική σελίδα;",
	typeLabel : "Τύπος Πεδίου",
	visibilityLabel : "Ορατό στον παίκτη",
	envyText : " Παιχνίδι για την αειφορία και την περιβαλλοντική συνείδηση. ",
	perfectVilleText: " Παιχνίδι για τις επιλογές ενός πολίτη στην πόλη του ",
		eatingOutGame:  "myGame.openInstance('eatingOut_Gr', 4);",
	covidGame:  "myGame.openInstance('covid19survivor_Gr', 4);",
	smartJacket:  "myGame.openInstance('smartJacket_Gr', 4);",
	perfectVilleGame:  "myGame.openInstance('perfectVille_Gr', 4);",
	shoppingGame:  "myGame.openInstance('shopping_Gr', 4);",
	sustTextiles:  "myGame.openInstance('sustTextiles_Gr', 4);",
	ancientGreek:  "myGame.openInstance('ancient_Gr', 4);",
	womanity:  "myGame.openInstance('womanity_Gr', 4);",
	ethics:  "myGame.openInstance('ethics_Gr', 4);",
	escapePlan:  "myGame.openInstance('escapePlan_Gr', 4);",
	nayplioGame:  "myGame.openInstance('nayplio_Gr', 4);",
	envyGame:  "myGame.openInstance('envyCity_Gr', 4);",
	eatingOutHBGame:  "myGame.openInstance('eatingOutHB_Gr', 4);",
	chefGame:  "myGame.openInstance('CTChef_Gr', 4);",
					 womanityText: " Παιχνίδι για την καθημερινότητα της σύγχρονης γυναίκας ",
	sustTextilesText: " Παιχνίδι για τη βιωσιμότητα στη βιομηχανία υφασμάτων ",
	badiText: " Παιχνίδι για την ισορροπημένη διατροφή ",
	 mpText: " Παιχνίδι για τα Αρχαία Ελληνικά  ",
	 supermarketText: " Παιχνίδι μαθηματικών σχέσεων  ",
	  covidText: "Παιχνίδι για την πανδημία του Covid-19",
	  ethicsText : " Παιχνίδι γα την επαγγελματική ηθική ",
		eatingTextHB: "Μισοψημένο παιχνίδι για την ισορροπημένη διατροφή",
		eatingText: "Παιχνίδι για την ισορροπημένη διατροφή",
chefText: "Μισοψημένο παιχνίδι για την Υπολογιστική Σκέψη και τη διαχείριση επιχειρήσεων",
schoolText: "Διασκευή μαθητών του παιχνιδιού 'Eating Out'",
europeText: "Διασκευή μαθητών του παιχνιδιού 'Eating Out'",
	//PLAY MODE
	pointInfoText : "Πληροφορίες Σημείου",
		gameStartedText : "Το παιχνίδι ξεκίνησε",
	gameValues: "Τιμές",
	pointsVisited: "Αριθμός Επιλογών",
	selectButton : "Επιλογή Σημείου",
	gameStatusText : "Κατάσταση Παιχνιδιού",
	deletePointText : "Διαγραφή Σημείου",
	gameOverMessage: "Το παιχνίδι τελείωσε!",
		gameOverQuestion: "Τι θα ήθελες να κάνεις;",
		editText: "Επεξεργάσου το παιχνίδι",
		playAgainText: "Παίξε ξανά",
		scoreText: "Δες το σκορ",
		gameEnded: "Τελος Παιχνιδιού!",
				gameEndedQuestion: "Τι θέλεις να κάνεις τώρα;",
				gameProgressText: "Στατιστικά Παιχνιδιού",
				currentValuesText: "Τωρινές τιμές πεδίων",
				choiceHistoryText: "Ιστορικό επιλογών",
						downloadScoreText: "Αποθήκευση σκορ",
						backBtnText: "Πίσω",
			letsPlayText: "Παίξε!",
			instructionsText: "Οδηγίες Παιχνιδιού",
			loadingMessage: "Το παιχνίδι φορτώνει...Παρακαλώ περιμένετε",
	popUpMessage : "Τέλος Παιχνιδιού! Έφτασες το μέγιστο όριο των επιτρεπόμενων κινήσεων <br>",
	gameInstructionsDefault : " Οδηγίες Παιχνιδιού: Κάνε κλίκ σε ένα σημείο για να δεις τις επιπτώσεις του στον πίνακα 'Πληροφορίες σημείου'. Μετά, κάνε κλικ στο κουμπί 'επιλογή σημείου' αν θέλεις να το επιλέξεις. Οι τιμές των παραμέτρων του παιχνιδιού αναγράφονται στον πίνακα 'Τιμές' πάνω από την περιοχή παιχνιδιού.",
	selBoxText: "Κείμενο",
	selBoxNum: "Αριθμός",
	selBoxUrl: "Σύνδεσμος",
	selBoxImage: "Εικόνα",
		selBoxDate: "Ημερομηνία",
	visBoxVisible: "Ορατό",
	visBoxHidden: "Κρυμμένο"
}
